#! /bin/bash

# Dieses Template basiert auf dem Default Template für Ubuntu 
# und führt erweiterte Konfigurationen am erstellten Container durch

HOMEDIR=$(dirname $0)
pushd $HOMEDIR >/dev/null

if [ ! -x lxc-ubuntu ]; then
	echo Failed because Ubuntu template not readable.
	exit 1
fi

# code

addAdditionalPackages() {
	echo Updating apt package list
	chroot $rootfs apt-get update >/dev/null
	
	echo Installing additional packages
	chroot $rootfs apt-get install --force-yes -y wget git htop  >/dev/null
	
	return 0
}

addAptProxy() {
	echo Adding apt-proxy
	echo "Acquire::http::Proxy \"http://freerunner.fritz.box:3142\";" > $rootfs/etc/apt/apt.conf.d/01proxy
	
	return 0
}


source lxc-ubuntu

echo Start processing Extensions...

if [ $? -ne 0 ]; then
    echo Extensions not processed because basic ubuntu template failed.
    exit 1
fi

addAptProxy
addAdditionalPackages

if [ $? -ne 0 ]; then
	echo Error while configuring extensions.
    exit 1
fi

popd >/dev/null

exit 0
