#! /bin/bash

# Dieses Template basiert auf dem Default Template für Ubuntu 
# und führt erweiterte Konfigurationen am erstellten Container durch

HOME_DIR=$(dirname $0)
pushd $HOME_DIR >/dev/null

if [ ! -x lxc-ubuntu ]; then
	echo Failed because Ubuntu template not readable.
	exit 1
fi

# DEFAULT CONFIGS
APT_PROXY_URL=http://localhost:3142
#http://freerunner.fritz.box:3142

# erwartet werden Configdateien mit Dateierweiterung.conf
CONFIG_DIR=conf.d
if [ -L -x $0 ]; then
	echo Template $(basename $0) is symlinked
	CONFIG_DIR=$(dirname$(readlink $0))/$CONFIG_DIR
else
	CONFIG_DIR=$HOME_DIR/$CONFIG_DIR
fi

echo $CONFIG_DIR

if [ ! -x lxc-ubuntu ]; then
	for f in $CONFIG_DIR/*.conf do
		echo $f
		source $CONFIG_DIR/$f
	done

exit 2

# code

addAdditionalPackages() {
	echo Updating apt package list
	chroot $rootfs apt-get update >/dev/null
	
	echo Installing additional packages
	chroot $rootfs apt-get install --force-yes -y wget git htop &>/dev/null

    return $?
}

addAptProxy() {
	echo Adding apt-proxy
	echo "Acquire::http::Proxy \"$APT_PROXY_URL\";" > $rootfs/etc/apt/apt.conf.d/01proxy
	
	return 0
}


source lxc-ubuntu

echo Start processing Extensions...

if [ $? -ne 0 ]; then
    echo Extensions not processed because basic ubuntu template failed.
    exit 1
fi

addAptProxy
addAdditionalPackages

if [ $? -ne 0 ]; then
	echo Error while configuring extensions.
    exit 1
fi

popd >/dev/null

exit 0
